Repository outerbase/astra-ui, pull requests merged in 2024-09, with the labels that each got.

#85 allow edit-on-return when a plugin is present
  src/components/table/core/td.ts
Labels: bugfix

#74 nested menu
  package.json
  src/components/astra-editor/plugins/sql-statement-highlight.ts
  src/components/astra-editor/plugins/sql.ts
  src/components/hans-wormhole.ts
  src/components/scroll-block.ts
  src/components/table/core/td.ts
  src/components/table/core/th.ts
  src/components/table/menu/cell-menu.ts
  src/components/table/menu/column-menu.ts
  src/components/table/menu/index.ts
  src/components/table/menu/input-menu.ts
  src/components/table/menu/item.ts
  src/components/table/menu/legacy.ts
  src/components/table/menu/trash.ts
  src/components/table/outerbase-table.ts
  src/components/universe/index.ts
  src/components/universe/plugins/handlebars.ts
  src/lib/events.ts
  src/pages/c/menu.astro
  src/pages/c/table.astro
  src/pages/index.astro
  src/types.ts
Labels: feature

#88 v0.3.3
  package.json
Labels: internal

#89 insert timestamp, uuid, null, undefined; fix border color; caret for sub items
  package.json
  pnpm-lock.yaml
  src/components/table/core/td.ts
  src/components/table/menu/index.ts
  src/pages/c/menu.astro
Labels: feature

#90 fix keyboard navigation of menu
  package.json
  src/components/table/menu/index.ts
Labels: bugfix

#92 horizontal virtualized scrolling
  package.json
  src/components/scroll-area.ts
  src/components/table/add-column.ts
  src/components/table/check-box.ts
  src/components/table/core/index.ts
  src/components/table/menu/index.ts
  src/components/table/outerbase-table.ts
  src/components/universe/index.ts
Labels: feature

#94 prevent editing / selecting checkbox cells
  src/components/table/core/td.ts
Labels: bugfix

#96 fix "revert" cell
  src/components/table/core/td.ts
  src/components/table/core/th.ts
  src/components/table/menu/index.ts
Labels: bugfix

#97 stop rendering new rows twice
  src/components/table/core/index.ts
Labels: bugfix

#95 v0.4.3
  package.json
Labels: internal

#98 ensure contents update when rows are changed
  src/components/table/core/index.ts
Labels: bugfix

#100 fix onkeydahn
  src/components/table/core/index.ts
Labels: bugfix

#101 v0.4.5
  package.json
Labels: internal

#104 delay call to update table view; reduce calls to update table view
  package.json
  src/components/table/core/index.ts
Labels: bugfix

#106 fix dark mode borders, adjust spacing/roundedness
  package.json
  src/components/table/menu/index.ts
Labels: bugfix

#111 fixing when prompt placeholder does not disappear
  src/components/astra-editor/plugins/prompt.ts
  src/index.ts
Labels: bugfix
