Repository outerbase/astra-ui, pull requests merged in 2024-07, with the labels that each got.

#38 prevent triggering editable state when cell is readonly
  src/components/table/td.ts
Labels: bug

#39 adjust class usage to employ proper css vars for row hover & table bg
  src/components/scroll-area.ts
  src/components/table/td.ts
Labels: bug

#37 support fetching data via starlink; refreshing; add and delete rows; discard; save; themes
  package.json
  pnpm-lock.yaml
  src/components/check-box.ts
  src/components/column-resizer-element.ts
  src/components/menu/cell-menu.ts
  src/components/menu/input-menu.ts
  src/components/mutable-element.ts
  src/components/outerbase-table.ts
  src/components/scroll-area.ts
  src/components/table/index.ts
  src/components/table/td.ts
  src/components/table/th.ts
  src/components/table/tr.ts
  src/icons/arrows-clockwise.ts
  src/icons/caret-left.ts
  src/icons/table.ts
  src/index.ts
  src/layouts/Layout.astro
  src/lib/diff-objects.ts
  src/lib/events.ts
  src/lib/normalize-object-keys.ts
  src/lib/stringify-without-new-lines.ts
  src/pages/index.astro
  src/pages/turso.astro
  src/types.ts
  tailwind.config.mjs
Labels: enhancement

#40 organize files
  src/bundle.ts
  src/components/classified-element.ts
  src/components/scroll-area.ts
  src/components/table/add-column.ts
  src/components/table/check-box.ts
  src/components/table/column-resizer-element.ts
  src/components/table/core/index.ts
  src/components/table/core/tbody.ts
  src/components/table/core/td.ts
  src/components/table/core/th.ts
  src/components/table/core/thead.ts
  src/components/table/core/tr.ts
  src/components/table/menu/cell-menu.ts
  src/components/table/menu/column-menu.ts
  src/components/table/menu/index.ts
  src/components/table/menu/input-menu.ts
  src/components/table/mutable-element.ts
  src/components/table/outerbase-table.ts
  src/index.ts
  src/pages/c/table.astro
  src/react.ts
  src/types.ts
Labels: enhancement

#34 add charts
  example.html
  package.json
  pnpm-lock.yaml
  src/bundle.ts
  src/components/calendar/calendar.ts
  src/components/charts/chart.ts
  src/components/charts/composed.ts
  src/components/table/core/td.ts
  src/index.ts
  src/lib/create-gradient.ts
  src/lib/random-contrasting-color.ts
  src/pages/index.astro
  src/react.ts
  src/types.ts
Labels: feature

#44 auto choose a schema + table name when none are specified
  src/bundle.ts
  src/components/table/outerbase-table.ts
Labels: feature

#45 Remove whitespace-pre in td
  package.json
  src/components/table/core/td.ts
Labels: bugfix

#46 add architecture diagrams/notes
  src/components/README.md
  src/components/calendar/README.md
  src/components/charts/README.md
  src/components/universe/README.md
Labels: internal
